name: PR done

on:
  workflow_run:
    workflows: ["pull request"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR stuff
        run: |
          echo "$EVENT" | jq
        env:
          EVENT: ${{ toJson(github.event) }}
