name: PR done

on:
  workflow_run:
    workflows: ["pull request"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR stuff
        run: |
          echo "$EVENT" | jq
        env:
          EVENT: ${{ toJson(github.event) }}
      - name: add PR comment
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        run: |
          gh pr -R ${{ github.event.repository.full_name }} comment ${{ github.event.workflow_run.pull_requests[0].number }} --body "PR done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
