name: PR done

on:
  workflow_run:
    workflows: ["pull request"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR stuff
        run: |
          echo "source id: {{ github.event.workflow_run.id }}"
          echo "source event: {{ github.event.workflow_run.event }}"
          echo "pull requests: {{ github.event.workflow_run.pull_requests }}"
